name: Deploy Backend
on:
  push:
    branches: [ main ] # Uruchomi się, gdy zrobisz push do main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      # Pakujemy backend do ZIPa (EB potrzebuje paczki z Dockerfile)
      - name: Generate Deployment Package
        run: zip -r deploy.zip . -x "frontend/**" "node_modules/**" ".git/**"

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'Twoja-Nazwa-Aplikacji' # wpisz nazwę z AWS EB
          environment_name: 'Twoja-Nazwa-Srodowiska-env' # wpisz nazwę środowiska z AWS EB
          version_label: "ver-${{ github.sha }}"
          region: eu-central-1 # Upewnij się, że region jest poprawny (np. eu-central-1 to Frankfurt)
          deployment_package: deploy.zip
