name: Deploy Backend
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Budujemy aplikację bezpośrednio na GitHubie
      - name: dotnet publish
        run: dotnet publish backend/SongSpiration.API/SongSpiration.API.csproj -c Release -o publish -r linux-x64 --self-contained false

      # Kopiujemy bazę danych do folderu publish, żeby była w paczce
      - name: Copy DB
        run: cp backend/SongSpiration.API/SongSpiration.db publish/

      # Pakujemy TYLKO Dockerfile i gotowe pliki binarne
      - name: Generate Deployment Package
        run: zip -r deploy.zip Dockerfile publish/

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'songspiration'
          environment_name: 'Songspiration-env'
          version_label: "ver-${{ github.sha }}"
          region: us-east-1
          deployment_package: deploy.zip
